### ISSUE TITLE
Feature request: Registration with "foreign" Registry

### ISSUE THREAD

**Issue by noheton** [FraunhoferIOSB/FAAAST-Service#159]
The FAAAST-Service seems very useful for automatic creation for AAS(-Environments) from existing definitions and also linking operational values and operations to assets.
I am currently missing a (configurable) functionality to register the resulting AAS with a foreign [Registry/Discovery](https://app.swaggerhub.com/apis/Plattform_i40/Registry-and-Discovery/V1.0RC01) API Server to enable distributed deployments.
e,g. the Docker [Basyx Registry Component](https://hub.docker.com/r/eclipsebasyx/aas-registry)
Are there any plans to integrate something along these lines soon?

Best regards,
Florian

**Comment by JensMueller2709** [comment]
Hello Florian,
thank you very much for your feature request!
You are absolutely right, the registration of AAS in an AAS Registry is a still missing functionality of the FA³ST Service. We already have this feature in our internal backlog and plan to implement it in the next weeks. At least this feature will be part of our release 1.0.0, which should be published at the end of this year at the latest. We aim to support any AAS Registry that is compliant with the AAS specification. 
However, in addition to the FA³ST service, we are developing other tools along the digital twin lifecycle. In the near future, we will publish an FA³ST registry, which is an implementation of the AAS registry. This might also be interesting for you.

Is this answer helpful for you?
If you have any other questions, do not hesitate to create other issues or comment to this issue.

Best,
Jens

**Comment by JensMueller2709** [comment]
We are happy to hear that you already started playing with the FA³ST Service. If you have any issues, questions or further feature request, you can just open issues. 

One of the key features of the FA³ST Service is the concept of Asset Connection. This component enables an easy connection to physical assets with arbitrary protocols. At this time, we implemented Asset Connections for OPCUA, MQTT and HTTP [see here](https://github.com/FraunhoferIOSB/FAAAST-Service/tree/main/assetconnection)). We want expand this list with much more protocols. However, if you require a protocol which is still missing, you can implement the Asset Connection interface at your own and plug it to the FA³ST Service through adding it to the configuration file. With the Asset Connection you can couple any AAS Submodel-Element (also AAS-Operations) to an external system.

Regarding feedback to the V3 RC02: Thank you very much to your offer! We already collect some feedbacks internally and send them back to the Plattform I4.0. 

Best,
Jens
