### ISSUE TITLE
Inconsistent response to DELETE

### ISSUE THREAD

**Issue by Saalvage** [FraunhoferIOSB/FAAAST-Service#299]
**Describe the bug**
Deleting either returns status code 204 (expected) or status code 200 with a seemingly meaningless body (unexpected). This seems unintentional.

**To Reproduce**
1.  Load model: https://github.com/FraunhoferIOSB/FAAAST-Service/blob/main/core/src/test/resources/AASFull.json
2.  DELETE `http://localhost:8080/shells/aHR0cHM6Ly9hY3BsdC5vcmcvVGVzdF9Bc3NldEFkbWluaXN0cmF0aW9uU2hlbGw=/aas/submodels/aHR0cDovL2FjcGx0Lm9yZy9TdWJtb2RlbHMvQXNzZXRzL1Rlc3RBc3NldC9JZGVudGlmaWNhdGlvbg==/` -> 204
3. Restart service
4.  DELETE `http://localhost:8080/submodels/aHR0cDovL2FjcGx0Lm9yZy9TdWJtb2RlbHMvQXNzZXRzL1Rlc3RBc3NldC9JZGVudGlmaWNhdGlvbg==/` -> 200

**Expected behavior**
Consistent status code 204.

**Additional context**
When which status code is returned seems inconsistent. As seen above deleting the same submodel via the Submodel Repository Interface returns 200, while deleting it via the Asset Administration Shell Interface returns 204. Deleting a submodel element seems to return 200 no matter the interface used, while deleting a shell always returns 204.

**Comment by mjacoby** [comment]
Thank you for your feedback and sorry for the delayed answer. I have just pushed an update an FA³ST Service should now correctly return 204 for all DELETE requests. 

You can find the latest changes on the main branch (commit https://github.com/FraunhoferIOSB/FAAAST-Service/commit/07162fe920cc1ec706eac09972ca5cf12bed229c) and once the CI pipeline is finished (~15min after this post) you can also find it as [pre-compiled JAR](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=de.fraunhofer.iosb.ilt.faaast.service&a=starter&v=0.5.0-SNAPSHOT) or as docker container (fraunhoferiosb/faaast-service:latest).

It would be highly appreciated if you can check if this resolves the bug and if so close this issue.

**Comment by Saalvage** [comment]
Thank you for getting back to me! The bug has been resolved with the indicated release!
