### ISSUE TITLE
Passing a submodel id for a shell id (and vice versa) results in internal server error

### ISSUE THREAD

**Issue by Saalvage** [FraunhoferIOSB/FAAAST-Service#326]
**Describe the bug**
The following body is returned when passing a `submodelIdentifier` as an `aasIdentifier`:
```json
{
  "success" : false,
  "messages" : [ {
    "messageType" : "Exception",
    "text" : "class io.adminshell.aas.v3.model.impl.DefaultSubmodel cannot be cast to class io.adminshell.aas.v3.model.AssetAdministrationShell (io.adminshell.aas.v3.model.impl.DefaultSubmodel and io.adminshell.aas.v3.model.AssetAdministrationShell are in unnamed module of loader 'app')",
    "code" : "",
    "timestamp" : "2023-01-20T00:00:06.123+00:00"
  } ]
}
```

**To Reproduce**
1.  Load model: https://github.com/FraunhoferIOSB/FAAAST-Service/blob/main/core/src/test/resources/AASFull.json
2.  GET `http://localhost:8080/shells/aHR0cDovL2FjcGx0Lm9yZy9TdWJtb2RlbHMvQXNzZXRzL1Rlc3RBc3NldC9JZGVudGlmaWNhdGlvbg==/` -> 500

**Expected behavior**
Consistent status code 404.

**Additional context**
The inverse (using an AAS id for a submodel id) results in the same kind of error, except when an AAS is specified in the URL.
`http://localhost:8080/submodels/aHR0cHM6Ly9hY3BsdC5vcmcvVGVzdF9Bc3NldEFkbWluaXN0cmF0aW9uU2hlbGw=/submodel` - exhibits bug
`http://localhost:8080/shells/aHR0cHM6Ly9hY3BsdC5vcmcvVGVzdF9Bc3NldEFkbWluaXN0cmF0aW9uU2hlbGw=/aas/submodels/aHR0cHM6Ly9hY3BsdC5vcmcvVGVzdF9Bc3NldEFkbWluaXN0cmF0aW9uU2hlbGw=/submodel` - 404 as expected

If a shell and a submodel share an id then the submodel (the AAS works just fine) is unable to be accessed in any way as 500 is always returned (although I'm not sure if such a model is considered valid - if it isn't the model validation should probably catch it).

I don't know the inner workings of Fa³st but it seems unusual that submodels and shells both appear to be looked for in a common place.

**Comment by mjacoby** [comment]
According to the specification, Identifiers have to be globally unique, i.e. this problem should never be able to occur.

However, you are correct that this should be identified by the validation process which it currently is not.
If you are interested in the details, the reason for that is that FA³ST is using a third party library for validation (https://github.com/admin-shell-io/java-serializer, which is currently in the process of becoming Eclipse AAS4j https://github.com/eclipse-aas4j/aas4j). The validator in this library only checks for constraints explicitely defined in the specification and unfortunately the specfication does not introduce an explicit constraint for uniqueness of identifiers.

Regarding your surprise `that submodels and shells both appear to be looked for in a common place` - the reason for this is that both derive from the same parent class `Identifiable` as defined in the meta model in the AAS specficiation and the persistence interface in FA³ST only defines a single method to access Identifiables with the intention to make implementation for different persistent backends easier.

To address this issue, validation should be improved to check for uniqueness of identifiers and also FA³ST should provide proper response codes even if validation is not actived. I'll add the FA³ST part to our backlog and check with AAS4j (which I'm also part of the developer team) to add this constraint. As it might take a while for a new release of AAS4j to happen (as we are currently working on moving to the latest v3.0 version of the specification), we might consider adding this validation inside FA³ST for now and remove it again once AAS4j supports this.

**Comment by Saalvage** [comment]
Actually, even for a conformant model you would receive status code 500 instead of 404 when erroneously trying to use a submodel id in place of a shell id, which I assume is unwanted behavior.
