### ISSUE TITLE
Question regarding OPC UA Crawler

### ISSUE THREAD

**Issue by wlkrm** [FraunhoferIOSB/FAAAST-Service#327]
Hello,

on your website, you mentioned an OPC UA Crawler (Automatisierte Erzeugung von Modellen auf Basis eines OPC UA Servers). Is this feature already available, or is it still in development, so I could contribute?

**Comment by mjacoby** [comment]
Thank you for your interest in FA³ST! 
Unfortunatelly, the mentioned OPC UA crawler is not public and there are currently no plans on publishing it (at least in short term). Also, the crawler currently can only process OPC UA servers that are already AAS-compliant. 

We are planning to update the crawler to also support mapping of generic OPC UA server (meaning OPC UA server using any datamodel and not only AAS-compliant ones) to AAS. However, this activity will only start in the second half of this year. If you are interested in contributing you are welcome to watch the repository for upcoming activies or you can also get in touch with us via faaast@iosb.fraunhofer.de.
