### ISSUE TITLE
Inquiries about the scope of persistence service

### ISSUE THREAD

**Issue by jongunee** [FraunhoferIOSB/FAAAST-Service#506]
Hello,

According to the FA3ST Service documents, you are providing In-Memory Persistence and File-based Persistence service.

I am wondering you are developing Database-based Persistence Service?
If not, do you have a plan about this?

**Comment by mjacoby** [comment]
Yes, FA³ST Service currently supports in-memory persistence and file-based persistence.

Databased-based persistence is in our backlog but we are currently not actively developing this feature. However, we plan to do so in the future but at this time cannot provide any details on when this will be finished.

**Comment by jongunee** [comment]
Hi, I saw your feature "SMT-TimeSeriesData" in this repo.
I am also wondering submodeltemplate/timeseries features are available now.
It seems it is not released officially, can I use  these modules to connect db and store data

- de.fraunhofer.iosb.ilt.faaast.service.submodeltemplate.timeseries
- de.fraunhofer.iosb.ilt.faaast.service.submodeltemplate.timeseries-csv
- de.fraunhofer.iosb.ilt.faaast.service.submodeltemplate.timeseries-influx

**Comment by mjacoby** [comment]
The SMT TIme Series Data functionality is currently still in progress of being developed.

Of course you can have a look and also start experimenting with it. Basic functionality such as querying data via the _readRecords_ operation and connecting _LinkedSegments_ with an InfluxDB will more or less work. But please be aware this branch is still under development, which means that breaking changes can (and probably will) happen at any time, there is no documentation, and we will not provide any support until it is documented and merged into the main branch.
