### ISSUE TITLE
Question regarding OPC UA endpoint

### ISSUE THREAD

**Issue by alex0598** [FraunhoferIOSB/FAAAST-Service#555]
Hello,

Is it possible to create an ASS, Submodels, .. using the OPC UA endpoint configuration ?

**Comment by mjacoby** [comment]
No, this is not supported as the underlying OPC UA specification does not define this functionality.

However, if you start FA³ST Service with both HTTP and OPC UA endpoint, you can create/update/delete AAS, submodels, and other elements via HTTP while the changes will be reflected in OPC UA in case that helps with your use case.eeeeeeeeeeeee
