### ISSUE TITLE
OPC UA asset connection failed

### ISSUE THREAD

**Issue by walterwootz** [FraunhoferIOSB/FAAAST-Service#674]
**Describe the bug**
FAAAST is not able to connect to OPC UA demo server.

**To Reproduce**
Run [this car OPC UA demo server](https://github.com/Engineering-Research-and-Development/opc-ua-car-server) on port 5001
Run FAAST using the following:
java -jar starter\target\target\starter-0.6.0-SNAPSHOT.jar -c .\misc\examples\opcua.json -vvv

**opcua.json** is the following:
```opcua.json
{
    "core": {
        "requestHandlerThreadPoolSize": 2
    },
    "endpoints": [{
            "@class": "de.fraunhofer.iosb.ilt.faaast.service.endpoint.http.HttpEndpoint",
            "port": 8080
        },
        {
            "@class": "de.fraunhofer.iosb.ilt.faaast.service.endpoint.opcua.OpcUaEndpoint",
            "tcpPort": 8081
        }],
    "persistence": {
        "@class": "de.fraunhofer.iosb.ilt.faaast.service.persistence.memory.PersistenceInMemory"
    },
    "messageBus": {
        "@class": "de.fraunhofer.iosb.ilt.faaast.service.messagebus.internal.MessageBusInternal"
    },
    "assetConnections": [
        {
            "@class": "de.fraunhofer.iosb.ilt.faaast.service.assetconnection.opcua.OpcUaAssetConnection",
            "host": "opc.tcp://localhost:5001",
            "supportedAuthentications": ["Anonymous"],
            "securityPolicy": "None",
            "securityMode" : "None",
            "valueProviders":
            {
                "(Submodel)[IRI]urn:aas:id:example:submodel:1,(Property)[ID_SHORT]Engine_Temperature":
                {
                    "nodeId": "ns=3;s=Temperature"
                },
                "(Submodel)[IRI]urn:aas:id:example:submodel:1,(Property)[ID_SHORT]Engine_Oxigen":
                {
                    "nodeId": "ns=3;s=Oxigen"
                }
            },
            "operationProviders":
            {
            },
            "subscriptionProviders":
            {
            }
        }
    ]
}

```

I also have not used "operationProviders" and "subscriptionProviders" at all for simplicity.

**Expected behavior**
FAAAST should run correctly, establishing connection to the OPC UA server. I'm able to do so using the prosys opcua client without any security configuration (all "None"), so I don't understand why prosys java client is not able to establish a connection.

**Output**
[TRACE] Establishing asset connection failed (endpoint: opc.tcp://localhost:5001) (de.fraunhofer.iosb.ilt.faaast.service.assetconnection.AssetConnectionManager)

Thank you very much!

**Comment by mjacoby** [comment]
Thank you for your feedback. Unfortunately, I was not able to reproduce the bug as for me it is working as expected using your [car OPC UA demo server](https://github.com/Engineering-Research-and-Development/opc-ua-car-server) and your config

> 2024-02-05 09:52:17 Connecting to assets...
2024-02-05 09:52:23 Asset connection established (endpoint: opc.tcp://localhost:5001)
2024-02-05 09:52:23 FA³ST Service successfully started

Could the error be caused by something on your machine like firewall settings or something similar?

If this does not resolve the issue please also provide the model file and a detail description of which version of FA³ST you are running ( I did try it with the latest released SNAPSHOT as well as latest commit on main branch). In case your model is confidential and you do not want to post it on the internet you can also send it to faaast@iosb.fraunhofer.de

**Comment by walterwootz** [comment]
Hi @mjacoby, thank you for the quick answer.
I'm able to connect to the OPC UA server successfully using the prosys client gui, but indeed I will check firewall/network related issues. Regarding the version, I cloned the repo and run `mvn clean install` on main branch (commit 83ba6fa) using java 17.0.10 and maven 3.9.6. Maybe versions are not correct?

About the model, I have not specified any aas model file when running the .jar. Do I need one or faaast will use a default one?

**Comment by mjacoby** [comment]
Not specifying a model file while defining an asset connection with a value provider will most probably crash FA³ST (because the value provider is pointing to a model element that does not exist).

I just tested it and seems to crash only after establishing the asset connection, i.e. you should still get the message `Asset connection established (endpoint: opc.tcp://localhost:5001)` before FA³ST crashes. So for testing is connecting via OPC UA works no model is ok but only for that.

The tool chain you are using seems fine although I tested it locally using Java 17.0.7 and maven 3.6.3. 

Currently, my best bet is that the problem might be something related to your machine because I am not able to reproduce the  issue. If this isn't the case I'm not sure where to look next....maybe we could try creating a docker-compose setup that works or reproduces the problem.

**Comment by walterwootz** [comment]
I figured out that running FAAAST with an empty **valueProviders** array makes the opcua connection established.
`2024-02-05 16:36:05 Asset connection established (endpoint: opc.tcp://localhost:5001/UA/CarServer)`

It still does not work with the config I provided as example.

I have also defined AAS model as follow:
```json
{
    "id":"carserver_aas",
    "type":"AssetAdministrationShell",
    "schemaLocation": "http://www.admin-shell.io/aas/1/0 AAS.xsd http://www.admin-shell.io/IEC61360/1/0 IEC61360.xsd",
    "assetAdministrationShells": [
        {
            "id": "urn:wvergaraw1:NodeOPCUA-Server",
            "idShort": "CarServerAAS",
            "modelType": {
                "name": "AssetAdministrationShell"
            },
            "identification": {
                "idType": "Iri",
                "id": "https://github.com/Engineering-Research-and-Development/opc-ua-car-server"
            },
            "assetInformation":
            {
                "assetKind": "Instance",
                "globalAssetId":
                {
                    "keys": [
                        {
                            "idType": "Iri",
                            "type": "Asset",
                            "value": "https://example.org/Test_Asset"
                        }
                    ]
                },
                "billOfMaterial": [
                    {
                        "keys": [
                            {
                                "idType": "Iri",
                                "type": "Submodel",
                                "value": "http://example.org/Submodels/Assets/TestAsset/BillOfMaterial"
                            }
                        ]
                    }
                ]
            },
            "submodels": [
                {
                    "keys": [
                        {
                            "type": "Submodel",
                            "value": "http://example.org/car",
                            "idType": "Iri"
                        }
                    ]
                }
            ]
        }
    ],
    "submodels": [
        {
            "semanticId": {
                "keys": [
                    {
                        "idType": "Iri",
                        "type": "GlobalReference",
                        "value": "Car001"
                    }
                ]
            },
            "identification": {
                "idType": "Iri",
                "id": "https://example.com/car/1"
            },
            "idShort": "Car",
            "modelType": {
                "name": "Submodel"
            },
            "kind": "Instance",
            "submodelElements": [
                {
                    "value": "0",
                    "semanticId": {
                        "keys": [{
                            "idType": "Iri",
                            "type": "GlobalReference",
                            "value": "Car001"
                        }]
                    },
                    "idShort": "Temperature",
                    "modelType": {
                        "name": "Property"
                    },
                    "valueType": "float",
                    "kind": "Instance"
                }
            ]
        }
    ],
    "conceptDescriptions": [{
        "modelType":
        {
            "name": "ConceptDescription"
        },
        "administration":
        {
            "revision": "0",
            "version": "0.9"
        },
        "identification":
        {
            "idType": "Iri",
            "id": "https://example.org/Test_ConceptDescription"
        },
        "idShort": "TestConceptDescription",
        "isCaseOf": [
            {
                "keys": [
                    {
                        "idType": "Iri",
                        "type": "GlobalReference",
                        "value": "http://example.org/DataSpecifications/ConceptDescriptions/TestConceptDescription"
                    }
                ]
            }
        ],
        "description": [
            {
                "language": "en-us",
                "text": "An example concept description for the test application"
            },
            {
                "language": "de",
                "text": "Ein Beispiel-ConceptDescription für eine Test-Anwendung"
            }
        ]
    }
    ]
}
```

this is the config:

```json
{
    "core": {
        "requestHandlerThreadPoolSize": 2
    },
    "endpoints": [{
            "@class": "de.fraunhofer.iosb.ilt.faaast.service.endpoint.http.HttpEndpoint",
            "port": 8080
        }],
    "persistence": {
        "@class": "de.fraunhofer.iosb.ilt.faaast.service.persistence.memory.PersistenceInMemory"
    },
    "messageBus": {
        "@class": "de.fraunhofer.iosb.ilt.faaast.service.messagebus.internal.MessageBusInternal"
    },
    "assetConnections": [
        {
            "@class": "de.fraunhofer.iosb.ilt.faaast.service.assetconnection.opcua.OpcUaAssetConnection",
            "host": "opc.tcp://localhost:5001/UA/CarServer",
            "supportedAuthentications": ["Anonymous"],
            "securityPolicy": "None",
            "securityMode" : "None",
            "valueProviders":
            {
                "(Submodel)[IRI]http://example.org/car,(Property)[ID_SHORT]Temperature":
                {
                    "nodeId": "ns=3;s=Temperature"
                }
            },
            "operationProviders":
            {
            },
            "subscriptionProviders":
            {
            }
        }
    ]
}
```

**Comment by mjacoby** [comment]
I managed to reproduce your issue and found that the problem is an invalid value provider configuration.
In your config, the reference to the temperature property is 
<pre>
(Submodel)[IRI]http://<b>exa</b>mple.org/car,(Property)[ID_SHORT]Temperature
</pre>
where it should be

<pre>
(Submodel)[IRI]http<b>s</b>://example.com/car<b>/1</b>,(Property)[ID_SHORT]Temperature
</pre>

to fit the model. 
If this line is changed your model and configuration works and successfully can connect to the OPC UA server.

**Comment by walterwootz** [comment]
You are right, now I'm able to connect correctly with this edit. Thank you very much for the support!
