### ISSUE TITLE
Several datatypes not yet supported in OPC UA Endpoint

### ISSUE THREAD

**Issue by wildias12** [FraunhoferIOSB/FAAAST-Service#801]
**Description:**
Currently, the OPC UA endpoint of the Fa³st Service does not support several datatypes such as anyUri, date, and duration. This limitation affects the usage of the service in applications that require these datatypes.

**Steps to Reproduce:**

1. Configure the Fa³st Service with an OPC UA endpoint.
2. Attempt to use datatypes such as anyUri, date, and duration.
3. Observe the failure or lack of support for these datatypes.

**Expected Behavior:**
The service should support all mentioned datatypes, allowing their usage without issues.

**Actual Behavior:**
The datatypes anyUri, date, and duration are not supported, resulting in errors or limited functionality.

**Environment:**
- Fa³st Service version: 1.0.1
- AAS Package Explorer Version: 3
- Operating System: Windows 10 Home

Relevant Logs:
![image](https://github.com/FraunhoferIOSB/FAAAST-Service/assets/172388426/0a83bb0f-5e42-4514-82db-b2ed3a65d986)
Log description: Terminal output showing the error when attempting to use unsupported datatypes.

![image](https://github.com/FraunhoferIOSB/FAAAST-Service/assets/172388426/94cf8af5-0f57-4cc4-8bc3-070d77f16dfc)
Log description: UA Expert indicating that the OPC UA server cannot read the "Value" of certain datatypes.

**Comment by mjacoby** [comment]
You are correct, many data types are currently not supported by the OPC UA endpoint.
We are currently working on fixing this (see branch [opcua_endpoint_datatypes](https://github.com/FraunhoferIOSB/FAAAST-Service/tree/feature/opcua_endpoint_datatypes)).

**Comment by mjacoby** [comment]
We just finished implementing support all datatypes in OPC UA. be aware that multiple of the AAS datetypes cannot be mapped to an equivalent datatype in OPC UA and therefore are mapped to `string` (for details see https://faaast-service.readthedocs.io/en/latest/interfaces/endpoint.html#datatype-mapping).

You can find these changes in the main branch, in the [latest SNAPSHOT release](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=de.fraunhofer.iosb.ilt.faaast.service&a=starter&v=1.2.0-SNAPSHOT), or in the latest docker image `fraunhoferiosb/faaast-service:1.2.0-SNAPSHOT`.
