### ISSUE TITLE
PUT shells/[aasIdentifier]/submodels/[submodelIdentifier/submodel-elements/[idShortPath] fails for SubmodelElementList

### ISSUE THREAD

**Issue by MMuellerMitsubishi** [FraunhoferIOSB/FAAAST-Service#930]
**Describe the bug**
We have a submodel which uses the SubmodelElementList. There we want to update the information of one given submodel element in that list.
When trying to do the PUT we get the following error:

{
    "messages": [
        {
            "messageType": "Exception",
            "text": "Range [1, 2) out of bounds for length 1",
            "code": "",
            "timestamp": "2024-10-17T13:18:31.075+00:00"
        }
    ]
}

When we do a a GET on the same endpoint, the result is returned without an error

**To Reproduce**
1.  Start the environment with a AAS and a SM that uses the SubmodelElementList
2.  Get the idShort Path of one element from the list
3.  Create the JSON body with the update information
4.  Call PUT shells/[aasIdentifier]/submodels/[submodelIdentifier/submodel-elements/[idShortPath]

**Expected behavior**
SubmodelElement that is part of a list can be updated using the PUT method

**Output**
see above

**Additional context**
I can provide our initially loaded AAS environment and the exact request if you need it.

**Comment by MMuellerMitsubishi** [comment]
Thanks for your quick response.
In my model the properties that are part of the list do not have an idShort. Neither the ones in the submodel in the repos nor the one in the body of the PUT.

As I understood the AAS specification, there is no idShort the elements of an Submodel Element List. So I omitted them.

That's also what the AASX Package Explorer does when storing an AAS with a SML as JSON.

`{
  "assetAdministrationShells": [
    {
      "id": "www.example.com/ids/sm/0095_3112_0142_2283",
      "assetInformation": {
        "assetKind": "Instance"
      },
      "submodels": [
        {
          "type": "ModelReference",
          "keys": [
            {
              "type": "Submodel",
              "value": "www.example.com/ids/sm/0095_3112_0142_1583"
            }
          ]
        }
      ],
      "modelType": "AssetAdministrationShell"
    }
  ],
  "submodels": [
    {
      "idShort": "SM",
      "id": "www.example.com/ids/sm/0095_3112_0142_1583",
      "submodelElements": [
        {
          "idShort": "SML",
          "typeValueListElement": "SubmodelElement",
          "value": [
            {
              "valueType": "xs:string",
              "value": "1",
              "modelType": "Property"
            },
            {
              "valueType": "xs:string",
              "value": "2",
              "modelType": "Property"
            }
          ],
          "modelType": "SubmodelElementList"
        }
      ],
      "modelType": "Submodel"
    }
  ],
  "conceptDescriptions": []
}`

**Comment by mjacoby** [comment]
You are correct, my initial test was incorrect as it was using idShort for elements in SubmodelElementList which is not allowed. I did test it again with the model you provided and I was not able to reproduce the error in your original post.
However, I did find and fix an error that occurs when modifying a list that contains two elements that are exactly equal in all of their properties. 

Could you please provide the REST requests needed to reproduce your problem?

If you like you can also try the latest version on the main branch either by manually compiling, using the [latest SNAPSHOT jar file](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=de.fraunhofer.iosb.ilt.faaast.service&a=starter&v=1.2.0-SNAPSHOT) or the docker contrainer with tag `latest`. Maybe your problem has already been solved by the previous fix.

**Comment by MMuellerMitsubishi** [comment]
The issue is solved in latest snapshot that you have linked above.
Before I was using the release 1.1.0.

So issue is solved. Thanks for the support.
